

scrape_configs:
  - job_name: 'spring-application'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets:  ['app:8083']

  - job_name: 'rabbitmq'
    metrics_path: '/metrics'
    scrape_interval: 3s
    static_configs:
      - targets: ['host.docker.internal:15692']